# Generated by Django 5.2.8 on 2025-12-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('vencimientos', 'Alerta de Vencimientos'), ('produccion', 'Análisis de Producción'), ('cliente_top', 'Clientes Top'), ('anomalia', 'Detección de Anomalías'), ('compliance', 'Cumplimiento Normativo')], max_length=50)),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('orden_ejecucion', models.IntegerField(default=0, help_text='Orden en el que se ejecuta (0=primero)')),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros configurables para la regla (ej: {"dias": 30, "severidad": "critical"})')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('modificada_en', models.DateTimeField(auto_now=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('proxima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_resultado', models.JSONField(blank=True, null=True)),
                ('ultimo_error', models.TextField(blank=True, null=True)),
                ('total_ejecuciones', models.IntegerField(default=0)),
                ('ejecuciones_exitosas', models.IntegerField(default=0)),
                ('ejecuciones_fallidas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Regla de Negocio',
                'verbose_name_plural': 'Reglas de Negocio',
                'ordering': ['orden_ejecucion', 'nombre'],
                'indexes': [models.Index(fields=['activa', 'tipo'], name='rules_engin_activa_ead9f9_idx'), models.Index(fields=['-ultima_ejecucion'], name='rules_engin_ultima__fe9e13_idx'), models.Index(fields=['codigo'], name='rules_engin_codigo_535418_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutando', 'Ejecutando'), ('exitosa', 'Exitosa'), ('error', 'Error'), ('parcial', 'Ejecución Parcial')], default='pendiente', max_length=20)),
                ('resultado', models.JSONField(default=dict)),
                ('error_mensaje', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('parametros_utilizados', models.JSONField(default=dict, help_text='Parámetros usados en esta ejecución')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='rules_engine.rule')),
            ],
            options={
                'verbose_name': 'Ejecución de Regla',
                'verbose_name_plural': 'Ejecuciones de Reglas',
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['regla', '-inicio'], name='rules_engin_regla_i_213b76_idx'), models.Index(fields=['estado'], name='rules_engin_estado_dcb918_idx'), models.Index(fields=['-inicio'], name='rules_engin_inicio_7dd0eb_idx')],
            },
        ),
    ]
