# Generated by Django 4.2.26 on 2025-12-02 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polizas', '0003_remove_poliza_compania_delete_compania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_uf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_uf', models.DecimalField(blank=True, decimal_places=2, help_text='Valor UF al momento de la cobranza', max_digits=10, null=True)),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la cobranza')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite de pago')),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha real de pago', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('DEBITO_AUTOMATICO', 'Débito Automático')], max_length=20, null=True)),
                ('numero_documento', models.CharField(blank=True, help_text='Número de cheque, transferencia, etc.', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranzas', to='polizas.poliza')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobranzas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobranza',
                'verbose_name_plural': 'Cobranzas',
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['estado', 'fecha_vencimiento'], name='cobranzas_c_estado_973841_idx'), models.Index(fields=['poliza', 'estado'], name='cobranzas_c_poliza__2a5057_idx')],
            },
        ),
    ]
