# Generated by Django 5.2.8 on 2025-12-08 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0001_initial'),
        ('polizas', '0004_poliza_cluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranza',
            name='campo_pago_pendiente',
            field=models.CharField(blank=True, help_text='Campo del Excel que indicó pago pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='dias_atraso',
            field=models.IntegerField(default=0, help_text='Días de atraso si está vencida sin pagar'),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='fuente_etl',
            field=models.BooleanField(default=True, help_text='¿Se creó desde ETL/Upload?'),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='razon_alerta',
            field=models.CharField(blank=True, help_text='Razón de la alerta (atraso recurrente, caída de prima, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='tiene_alerta_financiera',
            field=models.BooleanField(default=False, help_text='¿Tiene alerta de riesgo financiero?'),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='tipo_cobranza',
            field=models.CharField(choices=[('PAGO_VIGENTE', 'Pago Vigente/Pendiente'), ('PAGO_VENCIDO', 'Pago Vencido'), ('RIESGO_FINANCIERO', 'Riesgo Financiero')], default='PAGO_VIGENTE', help_text='Clasificación contable de la cobranza', max_length=30),
        ),
        migrations.AddIndex(
            model_name='cobranza',
            index=models.Index(fields=['tipo_cobranza', 'estado'], name='cobranzas_c_tipo_co_d732e5_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranza',
            index=models.Index(fields=['tiene_alerta_financiera'], name='cobranzas_c_tiene_a_062a13_idx'),
        ),
    ]
