# Generated by Django 4.2.26 on 2025-12-06 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=10)),
                ('resultado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('BLOQUEADO', 'Bloqueado')], max_length=20)),
                ('codigo_estado', models.IntegerField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acceso',
                'verbose_name_plural': 'Logs de Acceso',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='auditorias__usuario_0732cb_idx'), models.Index(fields=['ip_address', '-timestamp'], name='auditorias__ip_addr_324f7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('READ', 'Leer'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión'), ('PERMISSION_DENIED', 'Acceso denegado'), ('ROLE_CHANGE', 'Cambio de rol'), ('PASSWORD_CHANGE', 'Cambio de contraseña')], max_length=20)),
                ('modulo', models.CharField(help_text='Ej: cobranzas, alertas, usuarios', max_length=100)),
                ('modelo', models.CharField(help_text='Ej: Cobranza, Alerta, User', max_length=100)),
                ('objeto_id', models.CharField(blank=True, help_text='ID del objeto modificado', max_length=100, null=True)),
                ('descripcion', models.TextField(help_text='Descripción de lo que se hizo')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Valores antes de la acción', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Valores después de la acción', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metodo_http', models.CharField(blank=True, help_text='GET, POST, PUT, DELETE, etc', max_length=10, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('rol_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', '-fecha_hora'], name='auditorias__usuario_a6133f_idx'), models.Index(fields=['modulo', '-fecha_hora'], name='auditorias__modulo_c1a41e_idx'), models.Index(fields=['accion', '-fecha_hora'], name='auditorias__accion_9928f4_idx')],
            },
        ),
    ]
