# Generated by Django 4.2.26 on 2025-12-06 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('upload', 'Carga de archivo'), ('process', 'Procesamiento de datos'), ('view', 'Visualización de datos'), ('update', 'Actualización de datos'), ('delete', 'Eliminación de datos'), ('ml_run', 'Ejecución de modelo ML'), ('report_generate', 'Generación de reporte'), ('export', 'Exportación de datos')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalles', models.JSONField(blank=True, help_text='Detalles adicionales en JSON', null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='auditorias__usuario_1fa25b_idx'), models.Index(fields=['accion', '-fecha_creacion'], name='auditorias__accion_d8bb06_idx')],
            },
        ),
    ]
