# Generated by Django 5.2.8 on 2025-12-06 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('polizas', '0004_poliza_cluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha_creacion', '-severidad'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.RemoveIndex(
            model_name='alerta',
            name='alertas_ale_categor_50b9ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='alerta',
            name='alertas_ale_estado_b56f4b_idx',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='alerta',
            name='severidad',
            field=models.CharField(choices=[('info', 'Informativa'), ('warning', 'Advertencia'), ('critical', 'Crítica')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('produccion_baja', 'Producción Baja'), ('crecimiento_negativo', 'Crecimiento Negativo'), ('cliente_riesgo', 'Cliente en Cluster de Bajo Rendimiento'), ('error_carga', 'Error en Carga de Datos'), ('manual', 'Alerta Manual'), ('vencimientos', 'Vencimientos'), ('cobranzas', 'Cobranzas'), ('importaciones', 'Importaciones'), ('sistema', 'Sistema')], default='manual', max_length=50),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tipo', 'estado'], name='alertas_ale_tipo_36edc4_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['estado', 'severidad'], name='alertas_ale_estado_b6a222_idx'),
        ),
    ]
