# Generated by Django 5.2.8 on 2025-12-06 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_alter_alerta_options_and_more'),
        ('clientes', '0001_initial'),
        ('polizas', '0004_poliza_cluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('severidad', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('estado_final', models.CharField(choices=[('nueva', 'Nueva'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada'), ('expirada', 'Expirada')], db_index=True, default='nueva', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('alerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_registros', to='alertas.alerta')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_alertas', to='clientes.cliente')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_alertas', to='polizas.poliza')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Alerta',
                'verbose_name_plural': 'Historiales de Alertas',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['estado_final', 'severidad'], name='alertas_ale_estado__eab60c_idx'), models.Index(fields=['cliente', 'creada_en'], name='alertas_ale_cliente_199d66_idx'), models.Index(fields=['-creada_en'], name='alertas_ale_creada__13ef62_idx'), models.Index(fields=['tipo', 'estado_final'], name='alertas_ale_tipo_bf87eb_idx')],
            },
        ),
    ]
