# Generated by Django 5.2.8 on 2025-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_alertahistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='confiable',
            field=models.BooleanField(default=True, help_text='False si la alerta se generó con datos desactualizados (>30 días)'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='razon_no_confiable',
            field=models.CharField(blank=True, help_text='Razón por la cual la alerta no es confiable', max_length=255),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('ML_RIESGO_PRODUCCION', 'ML: Riesgo de Producción Baja'), ('ML_VARIACION_NEGATIVA', 'ML: Variación Negativa Detectada'), ('ML_ANOMALIA', 'ML: Anomalía en Datos'), ('produccion_baja', 'Producción Baja'), ('crecimiento_negativo', 'Crecimiento Negativo'), ('cliente_riesgo', 'Cliente en Cluster de Bajo Rendimiento'), ('error_carga', 'Error en Carga de Datos'), ('manual', 'Alerta Manual'), ('vencimientos', 'Vencimientos'), ('cobranzas', 'Cobranzas'), ('importaciones', 'Importaciones'), ('sistema', 'Sistema')], default='manual', max_length=50),
        ),
    ]
