# Generated by Django 4.2.26 on 2025-12-13 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas', '0004_alerta_confiable_alerta_razon_no_confiable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibir_emails', models.BooleanField(default=True, help_text='¿Recibir notificaciones por email?')),
                ('notificar_criticas', models.BooleanField(default=True, help_text='Notificar alertas críticas')),
                ('notificar_advertencias', models.BooleanField(default=True, help_text='Notificar alertas de advertencia')),
                ('notificar_info', models.BooleanField(default=False, help_text='Notificar alertas informativas')),
                ('tipos_interes', models.JSONField(blank=True, default=list, help_text='Tipos de alerta para notificar (vacío = todos)')),
                ('frecuencia', models.CharField(choices=[('inmediata', 'Inmediata'), ('diaria', 'Resumen Diario'), ('semanal', 'Resumen Semanal')], default='inmediata', help_text='Frecuencia de notificaciones', max_length=20)),
                ('hora_notificacion', models.TimeField(blank=True, help_text='Hora para enviar resumen (si usa resumen)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pref_notificacion_alerta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación de Alerta',
                'verbose_name_plural': 'Preferencias de Notificación de Alertas',
            },
        ),
    ]
