# Generated by Django 4.2.26 on 2025-11-20 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('filas_insertadas', models.IntegerField(default=0)),
                ('filas_actualizadas', models.IntegerField(default=0)),
                ('filas_erroneas', models.IntegerField(default=0)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
