# Generated by Django 4.2.26 on 2025-12-06 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='uploads/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validando', 'Validando'), ('limpiando', 'Limpiando'), ('procesando', 'Procesando'), ('ml', 'Aplicando ML'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('detalles_procesamiento', models.JSONField(blank=True, help_text='Detalles del procesamiento', null=True)),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_carga'],
                'indexes': [models.Index(fields=['estado', '-fecha_carga'], name='importacion_estado_5d8b2f_idx'), models.Index(fields=['cargado_por', '-fecha_carga'], name='importacion_cargado_133199_idx')],
            },
        ),
    ]
