# Generated by Django 5.2.8 on 2025-12-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0002_dataupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='error_file',
            field=models.FileField(blank=True, help_text='CSV con filas de error', null=True, upload_to='upload_errors/'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='inserted_rows',
            field=models.IntegerField(default=0, help_text='Total de filas insertadas'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='processed_rows',
            field=models.IntegerField(default=0, help_text='Total de filas procesadas'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='updated_rows',
            field=models.IntegerField(default=0, help_text='Total de filas actualizadas'),
        ),
        migrations.CreateModel(
            name='ImportErrorRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='importaciones.dataupload')),
            ],
            options={
                'verbose_name': 'Error de Importación',
                'verbose_name_plural': 'Errores de Importación',
                'ordering': ['row_number'],
            },
        ),
    ]
