# Generated by Django 5.2.8 on 2025-12-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0003_dataupload_error_file_dataupload_inserted_rows_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFreshness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(db_index=True, help_text='RUT o ID del cliente', max_length=100, unique=True)),
                ('ultima_actualizacion', models.DateField(auto_now=True, db_index=True, help_text='Última vez que se actualizó información')),
                ('dias_sin_actualizacion', models.IntegerField(default=0, help_text='Días desde última actualización')),
                ('alerta_frescura', models.BooleanField(default=False, help_text='¿Requiere alerta por falta de actualización?')),
                ('fecha_ultima_carga', models.DateField(blank=True, help_text='Última carga de archivo', null=True)),
                ('registros_actualizados', models.IntegerField(default=0, help_text='Registros actualizados en última carga')),
                ('usuario_ultima_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_cliente_frescura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frescura de Datos',
                'verbose_name_plural': 'Frescura de Datos',
                'ordering': ['-ultima_actualizacion'],
                'indexes': [models.Index(fields=['cliente', '-ultima_actualizacion'], name='importacion_cliente_e68139_idx'), models.Index(fields=['alerta_frescura'], name='importacion_alerta__efaaf4_idx'), models.Index(fields=['dias_sin_actualizacion'], name='importacion_dias_si_112487_idx')],
            },
        ),
    ]
