# Generated by Django 5.2.8 on 2025-12-08 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0004_datafreshness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafreshness',
            name='ultima_actualizacion',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Última vez que se actualizó información'),
        ),
    ]
