# Generated by Django 5.2.8 on 2025-12-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0005_alter_datafreshness_ultima_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialimportacion',
            name='clientes_ingresados',
            field=models.IntegerField(default=0, help_text='Total de clientes procesados en esta importación'),
        ),
    ]
