# Generated by Django 4.2.26 on 2025-12-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0006_historialimportacion_clientes_ingresados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialimportacion',
            name='clientes_ingresados',
            field=models.IntegerField(default=0, help_text='Total de pólizas únicas procesadas en esta importación'),
        ),
    ]
