# Generated by Django 5.2.8 on 2025-12-15 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0007_alter_historialimportacion_clientes_ingresados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataupload',
            options={'ordering': ['-fecha_carga'], 'verbose_name': 'Carga de Datos', 'verbose_name_plural': 'Cargas de Datos'},
        ),
        migrations.AddField(
            model_name='dataupload',
            name='columnas_detectadas',
            field=models.JSONField(blank=True, help_text='Lista de columnas detectadas en el Excel', null=True),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='columnas_validadas',
            field=models.BooleanField(default=False, help_text='¿Se validaron las columnas?'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='descargado',
            field=models.BooleanField(default=False, help_text='¿Se descargó el archivo original?'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='errores_validacion',
            field=models.JSONField(blank=True, help_text='Errores encontrados en validación', null=True),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='fecha_descarga',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='nombre_archivo_original',
            field=models.CharField(blank=True, default='archivo.xlsx', help_text='Nombre original del archivo cargado', max_length=255),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='preview_filas',
            field=models.JSONField(blank=True, help_text='Primeras 5-10 filas para preview', null=True),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('validando', 'Validando'), ('limpiando', 'Limpiando'), ('procesando', 'Procesando'), ('ml', 'Aplicando ML'), ('completado', 'Completado'), ('error', 'Error')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='dataupload',
            index=models.Index(fields=['fecha_carga'], name='importacion_fecha_c_8598d2_idx'),
        ),
    ]
