# Generated by Django 5.2.8 on 2025-12-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0008_alter_dataupload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='nombre_archivo_original',
            field=models.CharField(blank=True, help_text='Nombre original del archivo cargado', max_length=255, null=True),
        ),
    ]
