# Generated by Django 4.2.26 on 2025-12-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comercial', 'Usuario Comercial'), ('auditor', 'Auditor / Viewer')], default='comercial', help_text='Rol del usuario para control de permisos', max_length=20),
        ),
    ]
