# Generated by Django 4.2.26 on 2025-12-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0002_alter_poliza_compania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='compania',
        ),
        migrations.DeleteModel(
            name='Compania',
        ),
    ]
