# Generated by Django 5.2.8 on 2025-12-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0003_remove_poliza_compania_delete_compania'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='cluster',
            field=models.IntegerField(blank=True, db_index=True, help_text='Cluster ML asignado', null=True),
        ),
    ]
