# Generated by Django 5.2.8 on 2025-12-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('polizas', '0004_poliza_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='datos_confiables',
            field=models.BooleanField(default=True, help_text='False si > 30 días sin actualizar'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='frescura_estado',
            field=models.CharField(choices=[('excelente', 'Excelente (0-7 días)'), ('bueno', 'Bueno (8-30 días)'), ('advertencia', 'Advertencia (31-60 días)'), ('critico', 'Crítico (>60 días)')], default='excelente', help_text='Indicador de confianza de datos', max_length=20),
        ),
        migrations.AddField(
            model_name='poliza',
            name='ultima_actualizacion',
            field=models.DateField(auto_now=True, help_text='Última fecha de importación/actualización'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['-ultima_actualizacion'], name='polizas_pol_ultima__1c8ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['frescura_estado'], name='polizas_pol_frescur_f9cce9_idx'),
        ),
    ]
